# Generated by Django 3.0.3 on 2021-12-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PFam',
            fields=[
                ('domain_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('domain_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('taxa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('clade', models.CharField(default='E', max_length=1)),
                ('genus', models.CharField(max_length=1000)),
                ('species', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('protein_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('sequence', models.CharField(max_length=1000)),
                ('length', models.IntegerField()),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genedata.Taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('pfam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genedata.PFam')),
                ('protein_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='domains', to='genedata.Protein')),
            ],
        ),
    ]
