# Generated by Django 3.0.3 on 2021-12-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0004_auto_20211223_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='protein_taxa', to='genedata.Taxonomy'),
        ),
    ]
