# Generated by Django 3.0.3 on 2021-12-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0007_auto_20211226_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxalinkprotein',
            name='taxa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genedata.Taxonomy'),
        ),
    ]
