# Generated by Django 3.0.3 on 2021-12-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0008_auto_20211226_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxalinkprotein',
            name='protein_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genedata.Protein'),
        ),
    ]
