# Generated by Django 3.0.3 on 2021-12-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0009_auto_20211226_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaLinkDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genedata.Domain')),
                ('taxa_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genedata.Taxonomy')),
            ],
        ),
    ]
