# Generated by Django 3.0.3 on 2021-12-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0010_taxalinkdomain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxalinkdomain',
            old_name='domain_id',
            new_name='pfam_id',
        ),
    ]
