# Generated by Django 3.0.3 on 2021-12-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0011_auto_20211226_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxalinkdomain',
            name='pfam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='genedata.PFam'),
        ),
        migrations.AlterField(
            model_name='taxalinkdomain',
            name='taxa_id',
            field=models.IntegerField(),
        ),
    ]
