# Generated by Django 3.0.3 on 2022-01-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0012_auto_20211226_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxalinkprotein',
            name='protein_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='taxalinkprotein',
            name='taxa_id',
            field=models.IntegerField(),
        ),
    ]
